feat: search support (#53)
I cannot test this locally, but it appears to work on when I enabled it on a different site with this theme.

I believe this is because of JS origin rules that limit connections to proper domain names and SSL.

Note that I had to remove a minify of the index.js script because of the following that should be fixed in the future:

```
Start building sites …
hugo v0.91.2+extended darwin/arm64 BuildDate=unknown
Error: Error building site: MINIFY: failed to transform index.js (application/javascript): unexpected ; in expression on line 89 and column 5
   89:     ;
           ^
```